/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QuizOption: typeof import('./src/components/quiz/QuizOption.vue')['default']
    QuizRoot: typeof import('./src/components/quiz/QuizRoot.vue')['default']
    RadioGroupIndicator: typeof import('radix-vue')['RadioGroupIndicator']
    RadioGroupItem: typeof import('radix-vue')['RadioGroupItem']
    RadioGroupRoot: typeof import('radix-vue')['RadioGroupRoot']
    ResultCard: typeof import('./src/components/quiz/ResultCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
